dist: bionic
language: python

python:
  - 3.7.1

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qqq luarocks
  - pip3 install pre-commit
  - luarocks install --local luacheck

script:
  - pre-commit run --all-files
  - $HOME/.luarocks/bin/luacheck .
